### ISSUE TITLE
Remove all saved searches button requires non-breaking space for NVDA, which adds subtle right padding

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-library#208]
**Describe the bug**

See https://github.com/platform-coop-toolkit/coop-library/pull/193#discussion_r386659376

**Comment by jhung** [comment]
The "Deselect All Languages" label is affected by this issue as well.

The accessibility tree shows a proper label, but NVDA appears to incorrectly pronounce the label with a span.

**Comment by jhung** [comment]
The solution @greatislander and I discussed was to create separate accessible text that provides a complete phrase instead of just a fragment.

This means that there will be a label for sighted use cases, and another label for accessibility. This will make it better for translations as translating full phrases is better than translating fragments.
